const cards = [
  { id: '10-C', image: '../cards/10-C.png', value: 10, status: 'turnDown' },
  { id: '10-D', image: '../cards/10-D.png', value: 10, status: 'turnDown' },
  { id: '10-H', image: '../cards/10-H.png', value: 10, status: 'turnDown' },
  { id: '10-S', image: '../cards/10-S.png', value: 10, status: 'turnDown' },
  { id: '2-C', image: '../cards/2-C.png', value: 2, status: 'turnDown' },
  { id: '2-D', image: '../cards/2-D.png', value: 2, status: 'turnDown' },
  { id: '2-H', image: '../cards/2-H.png', value: 2, status: 'turnDown' },
  { id: '2-S', image: '../cards/2-S.png', value: 2, status: 'turnDown' },
  { id: '3-C', image: '../cards/3-C.png', value: 3, status: 'turnDown' },
  { id: '3-D', image: '../cards/3-D.png', value: 3, status: 'turnDown' },
  { id: '3-H', image: '../cards/3-H.png', value: 3, status: 'turnDown' },
  { id: '3-S', image: '../cards/3-S.png', value: 3, status: 'turnDown' },
  { id: '4-C', image: '../cards/4-C.png', value: 4, status: 'turnDown' },
  { id: '4-D', image: '../cards/4-D.png', value: 4, status: 'turnDown' },
  { id: '4-H', image: '../cards/4-H.png', value: 4, status: 'turnDown' },
  { id: '4-S', image: '../cards/4-S.png', value: 4, status: 'turnDown' },
  { id: '5-C', image: '../cards/5-C.png', value: 5, status: 'turnDown' },
  { id: '5-D', image: '../cards/5-D.png', value: 5, status: 'turnDown' },
  { id: '5-H', image: '../cards/5-H.png', value: 5, status: 'turnDown' },
  { id: '5-S', image: '../cards/5-S.png', value: 5, status: 'turnDown' },
  { id: '6-C', image: '../cards/6-C.png', value: 6, status: 'turnDown' },
  { id: '6-D', image: '../cards/6-D.png', value: 6, status: 'turnDown' },
  { id: '6-H', image: '../cards/6-H.png', value: 6, status: 'turnDown' },
  { id: '6-S', image: '../cards/6-S.png', value: 6, status: 'turnDown' },
  { id: '7-C', image: '../cards/7-C.png', value: 7, status: 'turnDown' },
  { id: '7-D', image: '../cards/7-D.png', value: 7, status: 'turnDown' },
  { id: '7-H', image: '../cards/7-H.png', value: 7, status: 'turnDown' },
  { id: '7-S', image: '../cards/7-S.png', value: 7, status: 'turnDown' },
  { id: '8-C', image: '../cards/8-C.png', value: 8, status: 'turnDown' },
  { id: '8-D', image: '../cards/8-D.png', value: 8, status: 'turnDown' },
  { id: '8-H', image: '../cards/8-H.png', value: 8, status: 'turnDown' },
  { id: '8-S', image: '../cards/8-S.png', value: 8, status: 'turnDown' },
  { id: '9-C', image: '../cards/9-C.png', value: 9, status: 'turnDown' },
  { id: '9-D', image: '../cards/9-D.png', value: 9, status: 'turnDown' },
  { id: '9-H', image: '../cards/9-H.png', value: 9, status: 'turnDown' },
  { id: '9-S', image: '../cards/9-S.png', value: 9, status: 'turnDown' },
  { id: 'A-C', image: '../cards/A-C.png', value: 11, status: 'turnDown' },
  { id: 'A-D', image: '../cards/A-D.png', value: 11, status: 'turnDown' },
  { id: 'A-H', image: '../cards/A-H.png', value: 11, status: 'turnDown' },
  { id: 'A-S', image: '../cards/A-S.png', value: 11, status: 'turnDown' },
  // { id: 'J-B', image: '../cards/J-B.png', value: 10, status: 'turnDown' },
  { id: 'J-C', image: '../cards/J-C.png', value: 10, status: 'turnDown' },
  { id: 'J-D', image: '../cards/J-D.png', value: 10, status: 'turnDown' },
  { id: 'J-H', image: '../cards/J-H.png', value: 10, status: 'turnDown' },
  // { id: 'J-R', image: '../cards/J-R.png', value: 10, status: 'turnDown' },
  { id: 'J-S', image: '../cards/J-S.png', value: 10, status: 'turnDown' },
  { id: 'K-C', image: '../cards/K-C.png', value: 10, status: 'turnDown' },
  { id: 'K-D', image: '../cards/K-D.png', value: 10, status: 'turnDown' },
  { id: 'K-H', image: '../cards/K-H.png', value: 10, status: 'turnDown' },
  { id: 'K-S', image: '../cards/K-S.png', value: 10, status: 'turnDown' },
  { id: 'Q-C', image: '../cards/Q-C.png', value: 10, status: 'turnDown' },
  { id: 'Q-D', image: '../cards/Q-D.png', value: 10, status: 'turnDown' },
  { id: 'Q-H', image: '../cards/Q-H.png', value: 10, status: 'turnDown' },
  { id: 'Q-S', image: '../cards/Q-S.png', value: 10, status: 'turnDown' }
];

export default cards;
